# Generated by Django 3.2.5 on 2021-07-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(blank=True, choices=[('Arte', 'Arte'), ('Belleza', 'Belleza'), ('Negocios', 'Negocios'), ('Cinema y Actuación', 'Cinema y Actuación'), ('Cultura', 'Cultura'), ('DIY', 'DIY'), ('Baile', 'Baile'), ('Entretenimiento', 'Entretenimiento'), ('Familia', 'Familia'), ('Moda', 'Moda'), ('Fitness y Bienestar', 'Fitness y Bienestar'), ('Comida', 'Comida'), ('Decoración del Hogar', 'Decoración del Hogar'), ('Humor', 'Humor'), ('Estilo de vida', 'Estilo de vida'), ('Nutrición', 'Nutrición'), ('Medicina', 'Medicina'), ('Automoviles', 'Automoviles'), ('Motocicleta', 'Motocicleta'), ('Deporte', 'Deporte'), ('Musica', 'Musica'), ('Covers Musicales', 'Covers Musicales'), ('Naturaleza', 'Naturaleza'), ('Mascotas y Animales', 'Mascotas y Animales'), ('Espiritualidad', 'Espiritualidad'), ('Tecnologia', 'Tecnología'), ('Ciencia', 'Ciencia'), ('Educación', 'Educación'), ('Viajes', 'Viajes')], max_length=150, null=True)),
            ],
        ),
    ]
